#ifndef WSMWAYLANDGLOBAL_H
#define WSMWAYLANDGLOBAL_H

#include <QtGlobal>
#include <QLoggingCategory>

#if defined(LYCHEE_WSMWAYLAND)
#define LYCHEE_WSMWAYLAND_EXPORT Q_DECL_EXPORT
#else
#define LYCHEE_WSMWAYLAND_EXPORT Q_DECL_IMPORT
#endif

Q_DECLARE_LOGGING_CATEGORY(LYCHEE_WSMWAYLAND)

#endif // WSMWAYLANDGLOBAL_H
